/**
 * Visual design system from reference react-app.js:
 * Neutral background, blue accent (#1C35D4), Helvetica, clear hierarchy.
 */

import type { CSSProperties } from 'react'

export const theme = {
  colors: {
    background: '#F7F7F5',
    surface: '#FFFFFF',
    surfaceMuted: '#EAEAE8',
    surfaceMutedHover: '#DCDCDA',
    accent: '#1C35D4',
    text: '#050505',
    textMuted: 'rgba(5, 5, 5, 0.6)',
    textFaded: 'rgba(5, 5, 5, 0.4)',
    border: '#E5E5E3',
    borderStrong: '#050505',
  },
  font: {
    family: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    hero: { fontSize: 64, fontWeight: 700, letterSpacing: '-0.04em', lineHeight: 0.85, textTransform: 'uppercase' as const },
    section: { fontSize: 48, fontWeight: 600, letterSpacing: '-0.04em', lineHeight: 0.9 },
    sectionSup: { fontSize: 10, fontWeight: 600, marginLeft: 4 },
    label: { fontSize: 11, textTransform: 'capitalize' as const, letterSpacing: '0.02em', fontWeight: 500 },
    body: { fontSize: 13, lineHeight: 1.4 },
    bodySmall: { fontSize: 12 },
    meta: { fontSize: 11, opacity: 0.5 },
  },
}

export const styles: Record<string, CSSProperties> = {
  root: {
    backgroundColor: theme.colors.background,
    color: theme.colors.text,
    fontFamily: theme.font.family,
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    overflowX: 'hidden',
    WebkitFontSmoothing: 'antialiased',
  },
  appHeader: {
    backgroundColor: theme.colors.accent,
    color: '#FFFFFF',
    padding: '24px 24px',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 40,
    alignItems: 'start',
  },
  textHero: {
    fontSize: theme.font.hero.fontSize,
    textTransform: theme.font.hero.textTransform,
    lineHeight: theme.font.hero.lineHeight,
    fontWeight: theme.font.hero.fontWeight,
    letterSpacing: theme.font.hero.letterSpacing,
  },
  appDesc: {
    fontSize: theme.font.meta.fontSize,
    lineHeight: 1.3,
    maxWidth: 400,
    opacity: 0.9,
    marginTop: 'auto',
    alignSelf: 'flex-end',
  },
  headerLink: {
    color: '#FFFFFF',
    textDecoration: 'none',
    fontSize: theme.font.meta.fontSize,
    opacity: 0.8,
    cursor: 'pointer',
  },
  appNav: {
    backgroundColor: theme.colors.background,
    position: 'sticky',
    top: 0,
    zIndex: 100,
    padding: '16px 24px',
    borderBottom: '1px solid rgba(0,0,0,0.05)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  navTabs: {
    display: 'flex',
    gap: 32,
  },
  navTabBase: {
    fontSize: theme.font.body.fontSize,
    textDecoration: 'none',
    color: theme.colors.text,
    fontWeight: 500,
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    transition: 'opacity 0.2s',
    fontFamily: theme.font.family,
  },
  navTabInactive: {
    opacity: 0.4,
  },
  navTabActive: {
    opacity: 1,
  },
  navTabDisabled: {
    opacity: 0.35,
    cursor: 'not-allowed',
  },
  navMeta: {
    fontSize: theme.font.meta.fontSize,
    opacity: 0.5,
    display: 'flex',
    gap: 16,
  },
  main: {
    padding: '40px 24px',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 60,
  },
  sectionHeader: {
    marginBottom: 24,
    paddingTop: 12,
  },
  textSection: {
    fontSize: theme.font.section.fontSize,
    fontWeight: theme.font.section.fontWeight,
    letterSpacing: theme.font.section.letterSpacing,
    position: 'relative',
    display: 'inline-block',
    lineHeight: theme.font.section.lineHeight,
  },
  sup: {
    fontSize: theme.font.sectionSup.fontSize,
    fontWeight: theme.font.sectionSup.fontWeight,
    marginLeft: theme.font.sectionSup.marginLeft,
    top: '-1.5em',
    position: 'relative',
  },
  dataGrid: {
    display: 'grid',
    gridTemplateColumns: '280px 1fr',
    gap: 40,
    alignItems: 'start',
  },
  uploadZone: {
    background: theme.colors.surfaceMuted,
    height: 200,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    padding: 24,
    textAlign: 'center',
    transition: 'background 0.2s',
  },
  uploadZoneHover: {
    background: theme.colors.surfaceMutedHover,
  },
  uploadIcon: {
    fontSize: 32,
    marginBottom: 12,
    fontWeight: 300,
  },
  textLabel: {
    fontSize: theme.font.label.fontSize,
    textTransform: theme.font.label.textTransform,
    letterSpacing: theme.font.label.letterSpacing,
    fontWeight: theme.font.label.fontWeight,
  },
  textBody: {
    fontSize: theme.font.body.fontSize,
    lineHeight: theme.font.body.lineHeight,
    maxWidth: '60ch',
  },
  colType: {
    fontFamily: "'Courier New', monospace",
    fontSize: theme.font.meta.fontSize,
    background: theme.colors.text,
    color: '#FFFFFF',
    padding: '2px 6px',
    display: 'inline-block',
  },
  btn: {
    background: 'transparent',
    border: `1px solid ${theme.colors.text}`,
    padding: '12px 24px',
    fontSize: 12,
    textTransform: 'uppercase',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'inline-block',
    marginTop: 16,
    transition: 'all 0.2s',
    fontFamily: theme.font.family,
    color: theme.colors.text,
  },
  btnHover: {
    background: theme.colors.text,
    color: '#FFFFFF',
  },
  btnPrimary: {
    background: theme.colors.accent,
    color: '#FFFFFF',
    border: `1px solid ${theme.colors.accent}`,
  },
  btnPrimaryHover: {
    background: '#1528b8',
    borderColor: '#1528b8',
    color: '#FFFFFF',
  },
  suggestionCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    border: `1px solid ${theme.colors.border}`,
    background: theme.colors.surface,
    padding: 24,
    transition: 'opacity 0.2s',
  },
  suggestionTitle: {
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: '-0.03em',
    lineHeight: 1,
  },
  suggestionDesc: {
    fontSize: theme.font.bodySmall.fontSize,
    opacity: 0.6,
    maxWidth: '90%',
    lineHeight: 1.3,
  },
  chartContainer: {
    width: '100%',
    background: theme.colors.surface,
    padding: 24,
    border: `1px solid ${theme.colors.border}`,
  },
  tableHeader: {
    textAlign: 'left',
    fontWeight: 500,
    padding: '12px 0',
    borderBottom: `1px solid ${theme.colors.text}`,
    opacity: 0.6,
    fontSize: theme.font.body.fontSize,
  },
  tableCell: {
    padding: '16px 0',
    borderBottom: `1px solid ${theme.colors.border}`,
    verticalAlign: 'top' as const,
    fontSize: theme.font.body.fontSize,
  },
}
